-- Run this in a NEW Supabase SQL Editor query for a fresh project.
create extension if not exists pgcrypto;
create table if not exists public.students(
 id bigint generated by default as identity primary key,
 name text not null,email text unique not null,password text not null,
 roll_no text,department text,cgpa numeric(4,2) default 0 check(cgpa between 0 and 10),
 graduation_year integer,phone text,gender text,skills text[] default '{}',
 resume_url text,linkedin_url text,leetcode_url text,github_url text,city text,bio text,
 created_at timestamptz default now()
);
create table if not exists public.companies(
 id bigint generated by default as identity primary key,name text not null,email text,website text,industry text,location text,created_at timestamptz default now()
);
create table if not exists public.jobs(
 id bigint generated by default as identity primary key,company_id bigint not null references public.companies(id) on delete cascade,
 title text not null,description text default '',package text,min_cgpa numeric(4,2) default 0,
 required_skills text[] default '{}',location text,deadline date not null,openings integer default 1,created_at timestamptz default now()
);
create table if not exists public.applications(
 id bigint generated by default as identity primary key,student_id bigint not null references public.students(id) on delete cascade,
 job_id bigint not null references public.jobs(id) on delete cascade,status text not null default 'Applied',
 applied_at timestamptz default now(),updated_at timestamptz default now(),unique(student_id,job_id)
);
alter table public.students enable row level security; alter table public.companies enable row level security;
alter table public.jobs enable row level security; alter table public.applications enable row level security;
insert into public.students(name,email,password,roll_no,department,cgpa,graduation_year,skills)
values('Vikash Gupta','vikash@example.com','demo1234','26','CSE',8.90,2028,array['C++','Python','Java','DSA'])
on conflict(email) do nothing;
insert into public.companies(name,email,website,industry,location)
select 'TCS','hr@tcs.example','https://www.tcs.com','IT Services','Mumbai'
where not exists(select 1 from public.companies where name='TCS');
insert into public.companies(name,email,website,industry,location)
select 'Infosys','hr@infosys.example','https://www.infosys.com','IT Services','Pune'
where not exists(select 1 from public.companies where name='Infosys');
insert into public.jobs(company_id,title,description,package,min_cgpa,required_skills,location,deadline,openings)
select id,'Software Developer','Build and maintain software applications.','₹6 LPA',7.5,array['C++','Python'],'Mumbai','2026-09-30',10 from public.companies where name='TCS'
and not exists(select 1 from public.jobs where title='Software Developer');
insert into public.jobs(company_id,title,description,package,min_cgpa,required_skills,location,deadline,openings)
select id,'Graduate Engineer','Work on enterprise software projects.','₹5.5 LPA',7.0,array['Python','Java'],'Pune','2026-10-05',8 from public.companies where name='Infosys'
and not exists(select 1 from public.jobs where title='Graduate Engineer');
