import React,{useEffect,useState} from "react";
import{createRoot}from"react-dom/client";
import{LayoutDashboard,Briefcase,FileText,UserRound,Building2,LogOut,Users,CheckCircle2,Eye,Upload,Plus}from"lucide-react";
import"./styles.css";
const API=import.meta.env.VITE_API_URL||"http://127.0.0.1:5000";
async function api(path,o={}){let r=await fetch(API+path,{headers:o.body instanceof FormData?{}:{"Content-Type":"application/json"},...o});let d=await r.json();if(!r.ok)throw Error(d.message||"Request failed");return d}

function Auth({onLogin}){const[mode,setMode]=useState("login"),[role,setRole]=useState("student"),[form,setForm]=useState({email:"vikash@example.com",password:"demo1234",name:""}),[err,setErr]=useState("");
const go=async e=>{e.preventDefault();setErr("");try{let d=mode==="login"?await api("/api/auth/login",{method:"POST",body:JSON.stringify({...form,role})}):await api("/api/auth/register",{method:"POST",body:JSON.stringify(form)});onLogin(d.user)}catch(e){setErr(e.message)}};
return <div className="auth"><div className="auth-card"><div className="brand">PMS</div><h1>Placement Management System</h1><p>Student placement and recruitment portal</p>{mode==="login"&&<div className="seg"><button className={role==="student"?"on":""} onClick={()=>{setRole("student");setForm({...form,email:"vikash@example.com",password:"demo1234"})}}>Student</button><button className={role==="admin"?"on":""} onClick={()=>{setRole("admin");setForm({...form,email:"admin@example.com",password:"admin1234"})}}>Admin</button></div>}{mode==="register"&&<><label>Full name</label><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></>}<form onSubmit={go}><label>Email</label><input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><label>Password</label><input type="password" required minLength="6" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button className="primary full">{mode==="login"?"Login":"Create Student Account"}</button></form>{err&&<div className="error">{err}</div>}<button className="link" onClick={()=>setMode(mode==="login"?"register":"login")}>{mode==="login"?"New student? Create account":"Already registered? Login"}</button>{mode==="login"&&<small>Demo student: vikash@example.com / demo1234 · Admin: admin@example.com / admin1234</small>}</div></div>}

function App(){const[user,setUser]=useState(null),[page,setPage]=useState("dashboard");if(!user)return <Auth onLogin={setUser}/>;let nav=user.role==="student"?[["dashboard","Dashboard",LayoutDashboard],["jobs","Jobs",Briefcase],["applications","My Applications",FileText],["profile","My Profile",UserRound]]:[["dashboard","Dashboard",LayoutDashboard],["companies","Companies",Building2],["jobs","Jobs",Briefcase],["applications","All Applications",FileText]];return <div className="app"><aside><div className="logo">PMS<span>•</span></div><div className="user"><div className="avatar">{user.name[0]}</div><div><b>{user.name}</b><small>{user.role}</small></div></div>{nav.map(([id,l,I])=><button className={page===id?"nav active":"nav"} onClick={()=>setPage(id)} key={id}><I size={18}/>{l}</button>)}<button className="nav logout" onClick={()=>setUser(null)}><LogOut size={18}/>Logout</button></aside><main><header><div><small>PLACEMENT PORTAL</small><h2>{page==="profile"?"My Profile":page==="applications"?"Applications":page[0].toUpperCase()+page.slice(1)}</h2></div><span className="pill">{user.role}</span></header><section>{page==="dashboard"?<Dashboard/>:page==="jobs"?<Jobs user={user}/>:page==="applications"?<Applications user={user}/>:page==="profile"?<Profile user={user}/>:<Companies/>}</section></main></div>}

function Dashboard(){const[s,setS]=useState({});useEffect(()=>{api("/api/dashboard/stats").then(setS)},[]);return <><div className="hero"><div><small>WELCOME TO THE PORTAL</small><h1>Placement Management System</h1><p>Students discover opportunities. Admin manages recruitment.</p></div></div><div className="stats">{Object.entries({Students:s.students,Companies:s.companies,Jobs:s.jobs,Applications:s.applications,Selected:s.selected}).map(([k,v])=><div className="stat" key={k}><small>{k}</small><b>{v??0}</b></div>)}</div><div className="panel"><h3>System architecture</h3><div className="flow"><span>React.js + CSS</span><b>→</b><span>Flask REST API</span><b>→</b><span>Python validation</span><b>→</b><span>Supabase PostgreSQL</span></div></div></>}

function Jobs({user}){const[j,setJ]=useState([]),[msg,setMsg]=useState(""),[detail,setDetail]=useState(null);const load=()=>api("/api/jobs").then(setJ);useEffect(()=>{load()},[]);async function apply(id){try{let d=await api("/api/applications",{method:"POST",body:JSON.stringify({student_id:user.id,job_id:id})});setMsg(d.message)}catch(e){setMsg(e.message)}}return <><div className="section"><h3>Available Opportunities</h3><p>Jobs published by placement companies.</p></div>{msg&&<div className="success">{msg}</div>}<div className="grid">{j.map(x=><div className="card" key={x.id}><div className="row"><div className="company-logo">{x.company_name?.[0]}</div><span className="pill">Open</span></div><h3>{x.title}</h3><b>{x.company_name}</b><p>{x.location} · {x.package}</p><div className="tags">{(x.required_skills||[]).map(s=><span key={s}>{s}</span>)}</div><small>Minimum CGPA: {x.min_cgpa} · Deadline: {x.deadline}</small><div className="actions">{user.role==="student"&&<button className="primary small" onClick={()=>apply(x.id)}>Apply</button>}<button className="ghost small" onClick={()=>setDetail(x)}>Details</button></div></div>)}</div>{detail&&<div className="modal"><div className="modal-card"><button className="close" onClick={()=>setDetail(null)}>×</button><h2>{detail.title}</h2><p>{detail.description}</p><p><b>Company:</b> {detail.company_name}</p><p><b>Package:</b> {detail.package}</p><p><b>Minimum CGPA:</b> {detail.min_cgpa}</p><p><b>Skills:</b> {(detail.required_skills||[]).join(", ")}</p><p><b>Deadline:</b> {detail.deadline}</p>{user.role==="student"&&<button className="primary" onClick={()=>apply(detail.id)}>Apply Now</button>}</div></div>}</>}

function Applications({user}){const[a,setA]=useState([]),[companies,setCompanies]=useState([]),[view,setView]=useState(null);const load=async()=>{let [x,c]=await Promise.all([api("/api/applications"),api("/api/companies")]);setA(user.role==="student"?x.filter(y=>y.student_id===user.id):x);setCompanies(c)};useEffect(()=>{load()},[user]);async function change(id,status){await api(`/api/applications/${id}/status`,{method:"PUT",body:JSON.stringify({status})});load()}return <div className="panel"><div className="section"><h3>{user.role==="admin"?"Company Applications":"My Applications"}</h3><p>{user.role==="admin"?"Review candidate details for each company's applications.":"Track your placement application status."}</p></div><table><thead><tr><th>Student</th><th>Company</th><th>Position</th><th>Status</th>{user.role==="admin"&&<th>Candidate</th>}</tr></thead><tbody>{a.length?a.map(x=><tr key={x.id}><td>{x.student_name}</td><td>{x.company_name}</td><td>{x.job_title}</td><td><span className="status">{x.status}</span></td>{user.role==="admin"&&<td><button className="ghost small" onClick={()=>setView(x)}><Eye size={14}/>View Details</button><select value={x.status} onChange={e=>change(x.id,e.target.value)}>{["Applied","Shortlisted","Interview","Selected","Rejected"].map(s=><option key={s}>{s}</option>)}</select></td>}</tr>):<tr><td colSpan="5">No applications yet.</td></tr>}</tbody></table>{view&&<div className="modal"><div className="modal-card candidate"><button className="close" onClick={()=>setView(null)}>×</button><div className="profile-head"><div className="avatar big">{view.student.name?.[0]||"S"}</div><div><h2>{view.student.name}</h2><p>{view.student.email}</p></div></div><div className="detail-grid">{[["Roll No",view.student.roll_no],["Department",view.student.department],["CGPA",view.student.cgpa],["Phone",view.student.phone],["City",view.student.city],["Graduation",view.student.graduation_year]].map(([k,v])=><div><small>{k}</small><b>{v||"—"}</b></div>)}</div><p><b>Skills:</b> {(view.student.skills||[]).join(", ")||"—"}</p><p><b>Bio:</b> {view.student.bio||"—"}</p><div className="links">{view.student.linkedin_url&&<a href={view.student.linkedin_url} target="_blank">LinkedIn</a>}{view.student.leetcode_url&&<a href={view.student.leetcode_url} target="_blank">LeetCode</a>}{view.student.github_url&&<a href={view.student.github_url} target="_blank">GitHub</a>}{view.student.resume_url&&<a href={view.student.resume_url} target="_blank">Resume PDF</a>}</div></div></div>}</div>}

function Profile({user}){const[p,setP]=useState(null),[msg,setMsg]=useState("");useEffect(()=>{api(`/api/students/${user.id}`).then(setP)},[user.id]);if(!p)return <div className="panel">Loading...</div>;const save=async e=>{e.preventDefault();try{let d=await api(`/api/students/${user.id}`,{method:"PUT",body:JSON.stringify({...p,skills:String(p.skills||"").split(",").map(x=>x.trim()).filter(Boolean)})});setP(d);setMsg("Profile updated successfully.")}catch(e){setMsg(e.message)}};const upload=async e=>{let f=e.target.files[0];if(!f)return;let fd=new FormData();fd.append("resume",f);try{let d=await api(`/api/students/${user.id}/resume`,{method:"POST",body:fd});setP({...p,resume_url:d.resume_url});setMsg("Resume uploaded successfully.")}catch(e){setMsg(e.message)}};return <div className="panel"><div className="section"><h3>Edit Student Profile</h3><p>Keep your academic and professional details updated for recruiters.</p></div><form className="profile-form" onSubmit={save}><label>Name<input value={p.name||""} onChange={e=>setP({...p,name:e.target.value})}/></label><label>Roll No<input value={p.roll_no||""} onChange={e=>setP({...p,roll_no:e.target.value})}/></label><label>Department<input value={p.department||""} onChange={e=>setP({...p,department:e.target.value})}/></label><label>CGPA<input type="number" step=".01" value={p.cgpa||0} onChange={e=>setP({...p,cgpa:e.target.value})}/></label><label>Graduation Year<input value={p.graduation_year||""} onChange={e=>setP({...p,graduation_year:e.target.value})}/></label><label>Phone<input value={p.phone||""} onChange={e=>setP({...p,phone:e.target.value})}/></label><label>City<input value={p.city||""} onChange={e=>setP({...p,city:e.target.value})}/></label><label>Skills <small>comma separated</small><input value={Array.isArray(p.skills)?p.skills.join(", "):p.skills||""} onChange={e=>setP({...p,skills:e.target.value})}/></label><label>LinkedIn URL<input value={p.linkedin_url||""} onChange={e=>setP({...p,linkedin_url:e.target.value})}/></label><label>LeetCode URL<input value={p.leetcode_url||""} onChange={e=>setP({...p,leetcode_url:e.target.value})}/></label><label>GitHub URL<input value={p.github_url||""} onChange={e=>setP({...p,github_url:e.target.value})}/></label><label>Resume URL<input value={p.resume_url||""} onChange={e=>setP({...p,resume_url:e.target.value})}/></label><label className="wide">Bio<textarea rows="4" value={p.bio||""} onChange={e=>setP({...p,bio:e.target.value})}/></label><div className="upload wide"><label>Upload Resume PDF<input type="file" accept="application/pdf,.pdf" onChange={upload}/></label>{p.resume_url&&<a href={p.resume_url} target="_blank">Open uploaded resume</a>}</div><button className="primary wide">Save Profile</button></form>{msg&&<div className="success">{msg}</div>}</div>}

function Companies(){const[c,setC]=useState([]),[name,setName]=useState(""),[location,setLocation]=useState("");const load=()=>api("/api/companies").then(setC);useEffect(()=>{load()},[]);async function add(){if(!name)return;await api("/api/companies",{method:"POST",body:JSON.stringify({name,location,industry:"IT Services"})});setName("");setLocation("");load()}return <><div className="panel"><h3>Add Company</h3><div className="inline"><input placeholder="Company name" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Location" value={location} onChange={e=>setLocation(e.target.value)}/><button className="primary" onClick={add}><Plus size={16}/>Add</button></div></div><div className="grid">{c.map(x=><div className="card" key={x.id}><div className="company-logo">{x.name[0]}</div><h3>{x.name}</h3><p>{x.industry} · {x.location}</p></div>)}</div></>}

createRoot(document.getElementById("root")).render(<App/>);
